/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nfs_context {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rpc_context {
    _unused: [u8; 0],
}
pub type rpc_cb = ::std::option::Option<
    unsafe extern "C" fn(
        rpc: *mut rpc_context,
        status: ::std::os::raw::c_int,
        data: *mut ::std::os::raw::c_void,
        private_data: *mut ::std::os::raw::c_void,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rpc_pdu {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn rpc_get_fd(rpc: *mut rpc_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rpc_which_events(rpc: *mut rpc_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rpc_service(
        rpc: *mut rpc_context,
        revents: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rpc_get_error(rpc: *mut rpc_context) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn nfs_get_rpc_context(nfs: *mut nfs_context) -> *mut rpc_context;
}
unsafe extern "C" {
    pub fn rpc_nfs3_lookup_task(
        rpc: *mut rpc_context,
        cb: rpc_cb,
        args: *mut LOOKUP3args,
        private_data: *mut ::std::os::raw::c_void,
    ) -> *mut rpc_pdu;
}
unsafe extern "C" {
    pub fn rpc_nfs3_read_task(
        rpc: *mut rpc_context,
        cb: rpc_cb,
        buf: *mut ::std::os::raw::c_void,
        count: usize,
        args: *mut READ3args,
        private_data: *mut ::std::os::raw::c_void,
    ) -> *mut rpc_pdu;
}
unsafe extern "C" {
    pub fn rpc_nfs3_write_task(
        rpc: *mut rpc_context,
        cb: rpc_cb,
        args: *mut WRITE3args,
        private_data: *mut ::std::os::raw::c_void,
    ) -> *mut rpc_pdu;
}
unsafe extern "C" {
    pub fn rpc_nfs3_commit_task(
        rpc: *mut rpc_context,
        cb: rpc_cb,
        args: *mut COMMIT3args,
        private_data: *mut ::std::os::raw::c_void,
    ) -> *mut rpc_pdu;
}
unsafe extern "C" {
    pub fn rpc_nfs3_setattr_task(
        rpc: *mut rpc_context,
        cb: rpc_cb,
        args: *mut SETATTR3args,
        private_data: *mut ::std::os::raw::c_void,
    ) -> *mut rpc_pdu;
}
unsafe extern "C" {
    pub fn rpc_nfs3_mkdir_task(
        rpc: *mut rpc_context,
        cb: rpc_cb,
        args: *mut MKDIR3args,
        private_data: *mut ::std::os::raw::c_void,
    ) -> *mut rpc_pdu;
}
unsafe extern "C" {
    pub fn rpc_nfs3_create_task(
        rpc: *mut rpc_context,
        cb: rpc_cb,
        args: *mut CREATE3args,
        private_data: *mut ::std::os::raw::c_void,
    ) -> *mut rpc_pdu;
}
unsafe extern "C" {
    pub fn rpc_nfs3_readdirplus_task(
        rpc: *mut rpc_context,
        cb: rpc_cb,
        args: *mut READDIRPLUS3args,
        private_data: *mut ::std::os::raw::c_void,
    ) -> *mut rpc_pdu;
}
unsafe extern "C" {
    pub fn rpc_nfs3_rename_task(
        rpc: *mut rpc_context,
        cb: rpc_cb,
        args: *mut RENAME3args,
        private_data: *mut ::std::os::raw::c_void,
    ) -> *mut rpc_pdu;
}
pub type cookieverf3 = [::std::os::raw::c_char; 8usize];
pub type cookie3 = u64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nfs_fh3 {
    pub data: nfs_fh3__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nfs_fh3__bindgen_ty_1 {
    pub data_len: u32,
    pub data_val: *mut ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nfs_fh3__bindgen_ty_1"][::std::mem::size_of::<nfs_fh3__bindgen_ty_1>() - 16usize];
    ["Alignment of nfs_fh3__bindgen_ty_1"]
        [::std::mem::align_of::<nfs_fh3__bindgen_ty_1>() - 8usize];
    ["Offset of field: nfs_fh3__bindgen_ty_1::data_len"]
        [::std::mem::offset_of!(nfs_fh3__bindgen_ty_1, data_len) - 0usize];
    ["Offset of field: nfs_fh3__bindgen_ty_1::data_val"]
        [::std::mem::offset_of!(nfs_fh3__bindgen_ty_1, data_val) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nfs_fh3"][::std::mem::size_of::<nfs_fh3>() - 16usize];
    ["Alignment of nfs_fh3"][::std::mem::align_of::<nfs_fh3>() - 8usize];
    ["Offset of field: nfs_fh3::data"][::std::mem::offset_of!(nfs_fh3, data) - 0usize];
};
pub type filename3 = *mut ::std::os::raw::c_char;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct diropargs3 {
    pub dir: nfs_fh3,
    pub name: filename3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of diropargs3"][::std::mem::size_of::<diropargs3>() - 24usize];
    ["Alignment of diropargs3"][::std::mem::align_of::<diropargs3>() - 8usize];
    ["Offset of field: diropargs3::dir"][::std::mem::offset_of!(diropargs3, dir) - 0usize];
    ["Offset of field: diropargs3::name"][::std::mem::offset_of!(diropargs3, name) - 16usize];
};
pub const NF3REG: ftype3 = 1;
pub const NF3DIR: ftype3 = 2;
pub const NF3BLK: ftype3 = 3;
pub const NF3CHR: ftype3 = 4;
pub const NF3LNK: ftype3 = 5;
pub const NF3SOCK: ftype3 = 6;
pub const NF3FIFO: ftype3 = 7;
pub type ftype3 = ::std::os::raw::c_uint;
pub type mode3 = u32;
pub type uid3 = u32;
pub type gid3 = u32;
pub type size3 = u64;
pub type fileid3 = u64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct specdata3 {
    pub specdata1: u32,
    pub specdata2: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of specdata3"][::std::mem::size_of::<specdata3>() - 8usize];
    ["Alignment of specdata3"][::std::mem::align_of::<specdata3>() - 4usize];
    ["Offset of field: specdata3::specdata1"]
        [::std::mem::offset_of!(specdata3, specdata1) - 0usize];
    ["Offset of field: specdata3::specdata2"]
        [::std::mem::offset_of!(specdata3, specdata2) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nfstime3 {
    pub seconds: u32,
    pub nseconds: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nfstime3"][::std::mem::size_of::<nfstime3>() - 8usize];
    ["Alignment of nfstime3"][::std::mem::align_of::<nfstime3>() - 4usize];
    ["Offset of field: nfstime3::seconds"][::std::mem::offset_of!(nfstime3, seconds) - 0usize];
    ["Offset of field: nfstime3::nseconds"][::std::mem::offset_of!(nfstime3, nseconds) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fattr3 {
    pub type_: ftype3,
    pub mode: mode3,
    pub nlink: u32,
    pub uid: uid3,
    pub gid: gid3,
    pub size: size3,
    pub used: size3,
    pub rdev: specdata3,
    pub fsid: u64,
    pub fileid: fileid3,
    pub atime: nfstime3,
    pub mtime: nfstime3,
    pub ctime: nfstime3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of fattr3"][::std::mem::size_of::<fattr3>() - 88usize];
    ["Alignment of fattr3"][::std::mem::align_of::<fattr3>() - 8usize];
    ["Offset of field: fattr3::type_"][::std::mem::offset_of!(fattr3, type_) - 0usize];
    ["Offset of field: fattr3::mode"][::std::mem::offset_of!(fattr3, mode) - 4usize];
    ["Offset of field: fattr3::nlink"][::std::mem::offset_of!(fattr3, nlink) - 8usize];
    ["Offset of field: fattr3::uid"][::std::mem::offset_of!(fattr3, uid) - 12usize];
    ["Offset of field: fattr3::gid"][::std::mem::offset_of!(fattr3, gid) - 16usize];
    ["Offset of field: fattr3::size"][::std::mem::offset_of!(fattr3, size) - 24usize];
    ["Offset of field: fattr3::used"][::std::mem::offset_of!(fattr3, used) - 32usize];
    ["Offset of field: fattr3::rdev"][::std::mem::offset_of!(fattr3, rdev) - 40usize];
    ["Offset of field: fattr3::fsid"][::std::mem::offset_of!(fattr3, fsid) - 48usize];
    ["Offset of field: fattr3::fileid"][::std::mem::offset_of!(fattr3, fileid) - 56usize];
    ["Offset of field: fattr3::atime"][::std::mem::offset_of!(fattr3, atime) - 64usize];
    ["Offset of field: fattr3::mtime"][::std::mem::offset_of!(fattr3, mtime) - 72usize];
    ["Offset of field: fattr3::ctime"][::std::mem::offset_of!(fattr3, ctime) - 80usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct post_op_attr {
    pub attributes_follow: u32,
    pub post_op_attr_u: post_op_attr__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union post_op_attr__bindgen_ty_1 {
    pub attributes: fattr3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of post_op_attr__bindgen_ty_1"]
        [::std::mem::size_of::<post_op_attr__bindgen_ty_1>() - 88usize];
    ["Alignment of post_op_attr__bindgen_ty_1"]
        [::std::mem::align_of::<post_op_attr__bindgen_ty_1>() - 8usize];
    ["Offset of field: post_op_attr__bindgen_ty_1::attributes"]
        [::std::mem::offset_of!(post_op_attr__bindgen_ty_1, attributes) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of post_op_attr"][::std::mem::size_of::<post_op_attr>() - 96usize];
    ["Alignment of post_op_attr"][::std::mem::align_of::<post_op_attr>() - 8usize];
    ["Offset of field: post_op_attr::attributes_follow"]
        [::std::mem::offset_of!(post_op_attr, attributes_follow) - 0usize];
    ["Offset of field: post_op_attr::post_op_attr_u"]
        [::std::mem::offset_of!(post_op_attr, post_op_attr_u) - 8usize];
};
pub const NFS3_OK: nfsstat3 = 0;
pub const NFS3ERR_PERM: nfsstat3 = 1;
pub const NFS3ERR_NOENT: nfsstat3 = 2;
pub const NFS3ERR_IO: nfsstat3 = 5;
pub const NFS3ERR_NXIO: nfsstat3 = 6;
pub const NFS3ERR_ACCES: nfsstat3 = 13;
pub const NFS3ERR_EXIST: nfsstat3 = 17;
pub const NFS3ERR_XDEV: nfsstat3 = 18;
pub const NFS3ERR_NODEV: nfsstat3 = 19;
pub const NFS3ERR_NOTDIR: nfsstat3 = 20;
pub const NFS3ERR_ISDIR: nfsstat3 = 21;
pub const NFS3ERR_INVAL: nfsstat3 = 22;
pub const NFS3ERR_FBIG: nfsstat3 = 27;
pub const NFS3ERR_NOSPC: nfsstat3 = 28;
pub const NFS3ERR_ROFS: nfsstat3 = 30;
pub const NFS3ERR_MLINK: nfsstat3 = 31;
pub const NFS3ERR_NAMETOOLONG: nfsstat3 = 63;
pub const NFS3ERR_NOTEMPTY: nfsstat3 = 66;
pub const NFS3ERR_DQUOT: nfsstat3 = 69;
pub const NFS3ERR_STALE: nfsstat3 = 70;
pub const NFS3ERR_REMOTE: nfsstat3 = 71;
pub const NFS3ERR_BADHANDLE: nfsstat3 = 10001;
pub const NFS3ERR_NOT_SYNC: nfsstat3 = 10002;
pub const NFS3ERR_BAD_COOKIE: nfsstat3 = 10003;
pub const NFS3ERR_NOTSUPP: nfsstat3 = 10004;
pub const NFS3ERR_TOOSMALL: nfsstat3 = 10005;
pub const NFS3ERR_SERVERFAULT: nfsstat3 = 10006;
pub const NFS3ERR_BADTYPE: nfsstat3 = 10007;
pub const NFS3ERR_JUKEBOX: nfsstat3 = 10008;
pub type nfsstat3 = ::std::os::raw::c_uint;
pub const UNSTABLE: stable_how = 0;
pub const DATA_SYNC: stable_how = 1;
pub const FILE_SYNC: stable_how = 2;
pub type stable_how = ::std::os::raw::c_uint;
pub type offset3 = u64;
pub type count3 = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wcc_attr {
    pub size: size3,
    pub mtime: nfstime3,
    pub ctime: nfstime3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of wcc_attr"][::std::mem::size_of::<wcc_attr>() - 24usize];
    ["Alignment of wcc_attr"][::std::mem::align_of::<wcc_attr>() - 8usize];
    ["Offset of field: wcc_attr::size"][::std::mem::offset_of!(wcc_attr, size) - 0usize];
    ["Offset of field: wcc_attr::mtime"][::std::mem::offset_of!(wcc_attr, mtime) - 8usize];
    ["Offset of field: wcc_attr::ctime"][::std::mem::offset_of!(wcc_attr, ctime) - 16usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct pre_op_attr {
    pub attributes_follow: u32,
    pub pre_op_attr_u: pre_op_attr__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pre_op_attr__bindgen_ty_1 {
    pub attributes: wcc_attr,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pre_op_attr__bindgen_ty_1"]
        [::std::mem::size_of::<pre_op_attr__bindgen_ty_1>() - 24usize];
    ["Alignment of pre_op_attr__bindgen_ty_1"]
        [::std::mem::align_of::<pre_op_attr__bindgen_ty_1>() - 8usize];
    ["Offset of field: pre_op_attr__bindgen_ty_1::attributes"]
        [::std::mem::offset_of!(pre_op_attr__bindgen_ty_1, attributes) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pre_op_attr"][::std::mem::size_of::<pre_op_attr>() - 32usize];
    ["Alignment of pre_op_attr"][::std::mem::align_of::<pre_op_attr>() - 8usize];
    ["Offset of field: pre_op_attr::attributes_follow"]
        [::std::mem::offset_of!(pre_op_attr, attributes_follow) - 0usize];
    ["Offset of field: pre_op_attr::pre_op_attr_u"]
        [::std::mem::offset_of!(pre_op_attr, pre_op_attr_u) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct wcc_data {
    pub before: pre_op_attr,
    pub after: post_op_attr,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of wcc_data"][::std::mem::size_of::<wcc_data>() - 128usize];
    ["Alignment of wcc_data"][::std::mem::align_of::<wcc_data>() - 8usize];
    ["Offset of field: wcc_data::before"][::std::mem::offset_of!(wcc_data, before) - 0usize];
    ["Offset of field: wcc_data::after"][::std::mem::offset_of!(wcc_data, after) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct WRITE3args {
    pub file: nfs_fh3,
    pub offset: offset3,
    pub count: count3,
    pub stable: stable_how,
    pub data: WRITE3args__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct WRITE3args__bindgen_ty_1 {
    pub data_len: u32,
    pub data_val: *mut ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of WRITE3args__bindgen_ty_1"]
        [::std::mem::size_of::<WRITE3args__bindgen_ty_1>() - 16usize];
    ["Alignment of WRITE3args__bindgen_ty_1"]
        [::std::mem::align_of::<WRITE3args__bindgen_ty_1>() - 8usize];
    ["Offset of field: WRITE3args__bindgen_ty_1::data_len"]
        [::std::mem::offset_of!(WRITE3args__bindgen_ty_1, data_len) - 0usize];
    ["Offset of field: WRITE3args__bindgen_ty_1::data_val"]
        [::std::mem::offset_of!(WRITE3args__bindgen_ty_1, data_val) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of WRITE3args"][::std::mem::size_of::<WRITE3args>() - 48usize];
    ["Alignment of WRITE3args"][::std::mem::align_of::<WRITE3args>() - 8usize];
    ["Offset of field: WRITE3args::file"][::std::mem::offset_of!(WRITE3args, file) - 0usize];
    ["Offset of field: WRITE3args::offset"][::std::mem::offset_of!(WRITE3args, offset) - 16usize];
    ["Offset of field: WRITE3args::count"][::std::mem::offset_of!(WRITE3args, count) - 24usize];
    ["Offset of field: WRITE3args::stable"][::std::mem::offset_of!(WRITE3args, stable) - 28usize];
    ["Offset of field: WRITE3args::data"][::std::mem::offset_of!(WRITE3args, data) - 32usize];
};
pub type writeverf3 = [::std::os::raw::c_char; 8usize];
#[repr(C)]
#[derive(Copy, Clone)]
pub struct WRITE3resok {
    pub file_wcc: wcc_data,
    pub count: count3,
    pub committed: stable_how,
    pub verf: writeverf3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of WRITE3resok"][::std::mem::size_of::<WRITE3resok>() - 144usize];
    ["Alignment of WRITE3resok"][::std::mem::align_of::<WRITE3resok>() - 8usize];
    ["Offset of field: WRITE3resok::file_wcc"]
        [::std::mem::offset_of!(WRITE3resok, file_wcc) - 0usize];
    ["Offset of field: WRITE3resok::count"][::std::mem::offset_of!(WRITE3resok, count) - 128usize];
    ["Offset of field: WRITE3resok::committed"]
        [::std::mem::offset_of!(WRITE3resok, committed) - 132usize];
    ["Offset of field: WRITE3resok::verf"][::std::mem::offset_of!(WRITE3resok, verf) - 136usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct WRITE3resfail {
    pub file_wcc: wcc_data,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of WRITE3resfail"][::std::mem::size_of::<WRITE3resfail>() - 128usize];
    ["Alignment of WRITE3resfail"][::std::mem::align_of::<WRITE3resfail>() - 8usize];
    ["Offset of field: WRITE3resfail::file_wcc"]
        [::std::mem::offset_of!(WRITE3resfail, file_wcc) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct WRITE3res {
    pub status: nfsstat3,
    pub WRITE3res_u: WRITE3res__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union WRITE3res__bindgen_ty_1 {
    pub resok: WRITE3resok,
    pub resfail: WRITE3resfail,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of WRITE3res__bindgen_ty_1"]
        [::std::mem::size_of::<WRITE3res__bindgen_ty_1>() - 144usize];
    ["Alignment of WRITE3res__bindgen_ty_1"]
        [::std::mem::align_of::<WRITE3res__bindgen_ty_1>() - 8usize];
    ["Offset of field: WRITE3res__bindgen_ty_1::resok"]
        [::std::mem::offset_of!(WRITE3res__bindgen_ty_1, resok) - 0usize];
    ["Offset of field: WRITE3res__bindgen_ty_1::resfail"]
        [::std::mem::offset_of!(WRITE3res__bindgen_ty_1, resfail) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of WRITE3res"][::std::mem::size_of::<WRITE3res>() - 152usize];
    ["Alignment of WRITE3res"][::std::mem::align_of::<WRITE3res>() - 8usize];
    ["Offset of field: WRITE3res::status"][::std::mem::offset_of!(WRITE3res, status) - 0usize];
    ["Offset of field: WRITE3res::WRITE3res_u"]
        [::std::mem::offset_of!(WRITE3res, WRITE3res_u) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LOOKUP3args {
    pub what: diropargs3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LOOKUP3args"][::std::mem::size_of::<LOOKUP3args>() - 24usize];
    ["Alignment of LOOKUP3args"][::std::mem::align_of::<LOOKUP3args>() - 8usize];
    ["Offset of field: LOOKUP3args::what"][::std::mem::offset_of!(LOOKUP3args, what) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct LOOKUP3resok {
    pub object: nfs_fh3,
    pub obj_attributes: post_op_attr,
    pub dir_attributes: post_op_attr,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LOOKUP3resok"][::std::mem::size_of::<LOOKUP3resok>() - 208usize];
    ["Alignment of LOOKUP3resok"][::std::mem::align_of::<LOOKUP3resok>() - 8usize];
    ["Offset of field: LOOKUP3resok::object"]
        [::std::mem::offset_of!(LOOKUP3resok, object) - 0usize];
    ["Offset of field: LOOKUP3resok::obj_attributes"]
        [::std::mem::offset_of!(LOOKUP3resok, obj_attributes) - 16usize];
    ["Offset of field: LOOKUP3resok::dir_attributes"]
        [::std::mem::offset_of!(LOOKUP3resok, dir_attributes) - 112usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct LOOKUP3resfail {
    pub dir_attributes: post_op_attr,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LOOKUP3resfail"][::std::mem::size_of::<LOOKUP3resfail>() - 96usize];
    ["Alignment of LOOKUP3resfail"][::std::mem::align_of::<LOOKUP3resfail>() - 8usize];
    ["Offset of field: LOOKUP3resfail::dir_attributes"]
        [::std::mem::offset_of!(LOOKUP3resfail, dir_attributes) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct LOOKUP3res {
    pub status: nfsstat3,
    pub LOOKUP3res_u: LOOKUP3res__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union LOOKUP3res__bindgen_ty_1 {
    pub resok: LOOKUP3resok,
    pub resfail: LOOKUP3resfail,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LOOKUP3res__bindgen_ty_1"]
        [::std::mem::size_of::<LOOKUP3res__bindgen_ty_1>() - 208usize];
    ["Alignment of LOOKUP3res__bindgen_ty_1"]
        [::std::mem::align_of::<LOOKUP3res__bindgen_ty_1>() - 8usize];
    ["Offset of field: LOOKUP3res__bindgen_ty_1::resok"]
        [::std::mem::offset_of!(LOOKUP3res__bindgen_ty_1, resok) - 0usize];
    ["Offset of field: LOOKUP3res__bindgen_ty_1::resfail"]
        [::std::mem::offset_of!(LOOKUP3res__bindgen_ty_1, resfail) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LOOKUP3res"][::std::mem::size_of::<LOOKUP3res>() - 216usize];
    ["Alignment of LOOKUP3res"][::std::mem::align_of::<LOOKUP3res>() - 8usize];
    ["Offset of field: LOOKUP3res::status"][::std::mem::offset_of!(LOOKUP3res, status) - 0usize];
    ["Offset of field: LOOKUP3res::LOOKUP3res_u"]
        [::std::mem::offset_of!(LOOKUP3res, LOOKUP3res_u) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct COMMIT3args {
    pub file: nfs_fh3,
    pub offset: offset3,
    pub count: count3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of COMMIT3args"][::std::mem::size_of::<COMMIT3args>() - 32usize];
    ["Alignment of COMMIT3args"][::std::mem::align_of::<COMMIT3args>() - 8usize];
    ["Offset of field: COMMIT3args::file"][::std::mem::offset_of!(COMMIT3args, file) - 0usize];
    ["Offset of field: COMMIT3args::offset"][::std::mem::offset_of!(COMMIT3args, offset) - 16usize];
    ["Offset of field: COMMIT3args::count"][::std::mem::offset_of!(COMMIT3args, count) - 24usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct COMMIT3resok {
    pub file_wcc: wcc_data,
    pub verf: writeverf3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of COMMIT3resok"][::std::mem::size_of::<COMMIT3resok>() - 136usize];
    ["Alignment of COMMIT3resok"][::std::mem::align_of::<COMMIT3resok>() - 8usize];
    ["Offset of field: COMMIT3resok::file_wcc"]
        [::std::mem::offset_of!(COMMIT3resok, file_wcc) - 0usize];
    ["Offset of field: COMMIT3resok::verf"][::std::mem::offset_of!(COMMIT3resok, verf) - 128usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct COMMIT3resfail {
    pub file_wcc: wcc_data,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of COMMIT3resfail"][::std::mem::size_of::<COMMIT3resfail>() - 128usize];
    ["Alignment of COMMIT3resfail"][::std::mem::align_of::<COMMIT3resfail>() - 8usize];
    ["Offset of field: COMMIT3resfail::file_wcc"]
        [::std::mem::offset_of!(COMMIT3resfail, file_wcc) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct COMMIT3res {
    pub status: nfsstat3,
    pub COMMIT3res_u: COMMIT3res__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union COMMIT3res__bindgen_ty_1 {
    pub resok: COMMIT3resok,
    pub resfail: COMMIT3resfail,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of COMMIT3res__bindgen_ty_1"]
        [::std::mem::size_of::<COMMIT3res__bindgen_ty_1>() - 136usize];
    ["Alignment of COMMIT3res__bindgen_ty_1"]
        [::std::mem::align_of::<COMMIT3res__bindgen_ty_1>() - 8usize];
    ["Offset of field: COMMIT3res__bindgen_ty_1::resok"]
        [::std::mem::offset_of!(COMMIT3res__bindgen_ty_1, resok) - 0usize];
    ["Offset of field: COMMIT3res__bindgen_ty_1::resfail"]
        [::std::mem::offset_of!(COMMIT3res__bindgen_ty_1, resfail) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of COMMIT3res"][::std::mem::size_of::<COMMIT3res>() - 144usize];
    ["Alignment of COMMIT3res"][::std::mem::align_of::<COMMIT3res>() - 8usize];
    ["Offset of field: COMMIT3res::status"][::std::mem::offset_of!(COMMIT3res, status) - 0usize];
    ["Offset of field: COMMIT3res::COMMIT3res_u"]
        [::std::mem::offset_of!(COMMIT3res, COMMIT3res_u) - 8usize];
};
pub const DONT_CHANGE: time_how = 0;
pub const SET_TO_SERVER_TIME: time_how = 1;
pub const SET_TO_CLIENT_TIME: time_how = 2;
pub type time_how = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct set_mode3 {
    pub set_it: u32,
    pub set_mode3_u: set_mode3__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union set_mode3__bindgen_ty_1 {
    pub mode: mode3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_mode3__bindgen_ty_1"][::std::mem::size_of::<set_mode3__bindgen_ty_1>() - 4usize];
    ["Alignment of set_mode3__bindgen_ty_1"]
        [::std::mem::align_of::<set_mode3__bindgen_ty_1>() - 4usize];
    ["Offset of field: set_mode3__bindgen_ty_1::mode"]
        [::std::mem::offset_of!(set_mode3__bindgen_ty_1, mode) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_mode3"][::std::mem::size_of::<set_mode3>() - 8usize];
    ["Alignment of set_mode3"][::std::mem::align_of::<set_mode3>() - 4usize];
    ["Offset of field: set_mode3::set_it"][::std::mem::offset_of!(set_mode3, set_it) - 0usize];
    ["Offset of field: set_mode3::set_mode3_u"]
        [::std::mem::offset_of!(set_mode3, set_mode3_u) - 4usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct set_uid3 {
    pub set_it: u32,
    pub set_uid3_u: set_uid3__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union set_uid3__bindgen_ty_1 {
    pub uid: uid3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_uid3__bindgen_ty_1"][::std::mem::size_of::<set_uid3__bindgen_ty_1>() - 4usize];
    ["Alignment of set_uid3__bindgen_ty_1"]
        [::std::mem::align_of::<set_uid3__bindgen_ty_1>() - 4usize];
    ["Offset of field: set_uid3__bindgen_ty_1::uid"]
        [::std::mem::offset_of!(set_uid3__bindgen_ty_1, uid) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_uid3"][::std::mem::size_of::<set_uid3>() - 8usize];
    ["Alignment of set_uid3"][::std::mem::align_of::<set_uid3>() - 4usize];
    ["Offset of field: set_uid3::set_it"][::std::mem::offset_of!(set_uid3, set_it) - 0usize];
    ["Offset of field: set_uid3::set_uid3_u"]
        [::std::mem::offset_of!(set_uid3, set_uid3_u) - 4usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct set_gid3 {
    pub set_it: u32,
    pub set_gid3_u: set_gid3__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union set_gid3__bindgen_ty_1 {
    pub gid: gid3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_gid3__bindgen_ty_1"][::std::mem::size_of::<set_gid3__bindgen_ty_1>() - 4usize];
    ["Alignment of set_gid3__bindgen_ty_1"]
        [::std::mem::align_of::<set_gid3__bindgen_ty_1>() - 4usize];
    ["Offset of field: set_gid3__bindgen_ty_1::gid"]
        [::std::mem::offset_of!(set_gid3__bindgen_ty_1, gid) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_gid3"][::std::mem::size_of::<set_gid3>() - 8usize];
    ["Alignment of set_gid3"][::std::mem::align_of::<set_gid3>() - 4usize];
    ["Offset of field: set_gid3::set_it"][::std::mem::offset_of!(set_gid3, set_it) - 0usize];
    ["Offset of field: set_gid3::set_gid3_u"]
        [::std::mem::offset_of!(set_gid3, set_gid3_u) - 4usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct set_size3 {
    pub set_it: u32,
    pub set_size3_u: set_size3__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union set_size3__bindgen_ty_1 {
    pub size: size3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_size3__bindgen_ty_1"][::std::mem::size_of::<set_size3__bindgen_ty_1>() - 8usize];
    ["Alignment of set_size3__bindgen_ty_1"]
        [::std::mem::align_of::<set_size3__bindgen_ty_1>() - 8usize];
    ["Offset of field: set_size3__bindgen_ty_1::size"]
        [::std::mem::offset_of!(set_size3__bindgen_ty_1, size) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_size3"][::std::mem::size_of::<set_size3>() - 16usize];
    ["Alignment of set_size3"][::std::mem::align_of::<set_size3>() - 8usize];
    ["Offset of field: set_size3::set_it"][::std::mem::offset_of!(set_size3, set_it) - 0usize];
    ["Offset of field: set_size3::set_size3_u"]
        [::std::mem::offset_of!(set_size3, set_size3_u) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct set_atime {
    pub set_it: time_how,
    pub set_atime_u: set_atime__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union set_atime__bindgen_ty_1 {
    pub atime: nfstime3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_atime__bindgen_ty_1"][::std::mem::size_of::<set_atime__bindgen_ty_1>() - 8usize];
    ["Alignment of set_atime__bindgen_ty_1"]
        [::std::mem::align_of::<set_atime__bindgen_ty_1>() - 4usize];
    ["Offset of field: set_atime__bindgen_ty_1::atime"]
        [::std::mem::offset_of!(set_atime__bindgen_ty_1, atime) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_atime"][::std::mem::size_of::<set_atime>() - 12usize];
    ["Alignment of set_atime"][::std::mem::align_of::<set_atime>() - 4usize];
    ["Offset of field: set_atime::set_it"][::std::mem::offset_of!(set_atime, set_it) - 0usize];
    ["Offset of field: set_atime::set_atime_u"]
        [::std::mem::offset_of!(set_atime, set_atime_u) - 4usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct set_mtime {
    pub set_it: time_how,
    pub set_mtime_u: set_mtime__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union set_mtime__bindgen_ty_1 {
    pub mtime: nfstime3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_mtime__bindgen_ty_1"][::std::mem::size_of::<set_mtime__bindgen_ty_1>() - 8usize];
    ["Alignment of set_mtime__bindgen_ty_1"]
        [::std::mem::align_of::<set_mtime__bindgen_ty_1>() - 4usize];
    ["Offset of field: set_mtime__bindgen_ty_1::mtime"]
        [::std::mem::offset_of!(set_mtime__bindgen_ty_1, mtime) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of set_mtime"][::std::mem::size_of::<set_mtime>() - 12usize];
    ["Alignment of set_mtime"][::std::mem::align_of::<set_mtime>() - 4usize];
    ["Offset of field: set_mtime::set_it"][::std::mem::offset_of!(set_mtime, set_it) - 0usize];
    ["Offset of field: set_mtime::set_mtime_u"]
        [::std::mem::offset_of!(set_mtime, set_mtime_u) - 4usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct sattr3 {
    pub mode: set_mode3,
    pub uid: set_uid3,
    pub gid: set_gid3,
    pub size: set_size3,
    pub atime: set_atime,
    pub mtime: set_mtime,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sattr3"][::std::mem::size_of::<sattr3>() - 64usize];
    ["Alignment of sattr3"][::std::mem::align_of::<sattr3>() - 8usize];
    ["Offset of field: sattr3::mode"][::std::mem::offset_of!(sattr3, mode) - 0usize];
    ["Offset of field: sattr3::uid"][::std::mem::offset_of!(sattr3, uid) - 8usize];
    ["Offset of field: sattr3::gid"][::std::mem::offset_of!(sattr3, gid) - 16usize];
    ["Offset of field: sattr3::size"][::std::mem::offset_of!(sattr3, size) - 24usize];
    ["Offset of field: sattr3::atime"][::std::mem::offset_of!(sattr3, atime) - 40usize];
    ["Offset of field: sattr3::mtime"][::std::mem::offset_of!(sattr3, mtime) - 52usize];
};
pub const UNCHECKED: createmode3 = 0;
pub const GUARDED: createmode3 = 1;
pub const EXCLUSIVE: createmode3 = 2;
pub type createmode3 = ::std::os::raw::c_uint;
pub type createverf3 = [::std::os::raw::c_char; 8usize];
#[repr(C)]
#[derive(Copy, Clone)]
pub struct createhow3 {
    pub mode: createmode3,
    pub createhow3_u: createhow3__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union createhow3__bindgen_ty_1 {
    pub obj_attributes: sattr3,
    pub g_obj_attributes: sattr3,
    pub verf: createverf3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of createhow3__bindgen_ty_1"]
        [::std::mem::size_of::<createhow3__bindgen_ty_1>() - 64usize];
    ["Alignment of createhow3__bindgen_ty_1"]
        [::std::mem::align_of::<createhow3__bindgen_ty_1>() - 8usize];
    ["Offset of field: createhow3__bindgen_ty_1::obj_attributes"]
        [::std::mem::offset_of!(createhow3__bindgen_ty_1, obj_attributes) - 0usize];
    ["Offset of field: createhow3__bindgen_ty_1::g_obj_attributes"]
        [::std::mem::offset_of!(createhow3__bindgen_ty_1, g_obj_attributes) - 0usize];
    ["Offset of field: createhow3__bindgen_ty_1::verf"]
        [::std::mem::offset_of!(createhow3__bindgen_ty_1, verf) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of createhow3"][::std::mem::size_of::<createhow3>() - 72usize];
    ["Alignment of createhow3"][::std::mem::align_of::<createhow3>() - 8usize];
    ["Offset of field: createhow3::mode"][::std::mem::offset_of!(createhow3, mode) - 0usize];
    ["Offset of field: createhow3::createhow3_u"]
        [::std::mem::offset_of!(createhow3, createhow3_u) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CREATE3args {
    pub where_: diropargs3,
    pub how: createhow3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CREATE3args"][::std::mem::size_of::<CREATE3args>() - 96usize];
    ["Alignment of CREATE3args"][::std::mem::align_of::<CREATE3args>() - 8usize];
    ["Offset of field: CREATE3args::where_"][::std::mem::offset_of!(CREATE3args, where_) - 0usize];
    ["Offset of field: CREATE3args::how"][::std::mem::offset_of!(CREATE3args, how) - 24usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct post_op_fh3 {
    pub handle_follows: u32,
    pub post_op_fh3_u: post_op_fh3__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union post_op_fh3__bindgen_ty_1 {
    pub handle: nfs_fh3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of post_op_fh3__bindgen_ty_1"]
        [::std::mem::size_of::<post_op_fh3__bindgen_ty_1>() - 16usize];
    ["Alignment of post_op_fh3__bindgen_ty_1"]
        [::std::mem::align_of::<post_op_fh3__bindgen_ty_1>() - 8usize];
    ["Offset of field: post_op_fh3__bindgen_ty_1::handle"]
        [::std::mem::offset_of!(post_op_fh3__bindgen_ty_1, handle) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of post_op_fh3"][::std::mem::size_of::<post_op_fh3>() - 24usize];
    ["Alignment of post_op_fh3"][::std::mem::align_of::<post_op_fh3>() - 8usize];
    ["Offset of field: post_op_fh3::handle_follows"]
        [::std::mem::offset_of!(post_op_fh3, handle_follows) - 0usize];
    ["Offset of field: post_op_fh3::post_op_fh3_u"]
        [::std::mem::offset_of!(post_op_fh3, post_op_fh3_u) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CREATE3resok {
    pub obj: post_op_fh3,
    pub obj_attributes: post_op_attr,
    pub dir_wcc: wcc_data,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CREATE3resok"][::std::mem::size_of::<CREATE3resok>() - 248usize];
    ["Alignment of CREATE3resok"][::std::mem::align_of::<CREATE3resok>() - 8usize];
    ["Offset of field: CREATE3resok::obj"][::std::mem::offset_of!(CREATE3resok, obj) - 0usize];
    ["Offset of field: CREATE3resok::obj_attributes"]
        [::std::mem::offset_of!(CREATE3resok, obj_attributes) - 24usize];
    ["Offset of field: CREATE3resok::dir_wcc"]
        [::std::mem::offset_of!(CREATE3resok, dir_wcc) - 120usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CREATE3resfail {
    pub dir_wcc: wcc_data,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CREATE3resfail"][::std::mem::size_of::<CREATE3resfail>() - 128usize];
    ["Alignment of CREATE3resfail"][::std::mem::align_of::<CREATE3resfail>() - 8usize];
    ["Offset of field: CREATE3resfail::dir_wcc"]
        [::std::mem::offset_of!(CREATE3resfail, dir_wcc) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CREATE3res {
    pub status: nfsstat3,
    pub CREATE3res_u: CREATE3res__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union CREATE3res__bindgen_ty_1 {
    pub resok: CREATE3resok,
    pub resfail: CREATE3resfail,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CREATE3res__bindgen_ty_1"]
        [::std::mem::size_of::<CREATE3res__bindgen_ty_1>() - 248usize];
    ["Alignment of CREATE3res__bindgen_ty_1"]
        [::std::mem::align_of::<CREATE3res__bindgen_ty_1>() - 8usize];
    ["Offset of field: CREATE3res__bindgen_ty_1::resok"]
        [::std::mem::offset_of!(CREATE3res__bindgen_ty_1, resok) - 0usize];
    ["Offset of field: CREATE3res__bindgen_ty_1::resfail"]
        [::std::mem::offset_of!(CREATE3res__bindgen_ty_1, resfail) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CREATE3res"][::std::mem::size_of::<CREATE3res>() - 256usize];
    ["Alignment of CREATE3res"][::std::mem::align_of::<CREATE3res>() - 8usize];
    ["Offset of field: CREATE3res::status"][::std::mem::offset_of!(CREATE3res, status) - 0usize];
    ["Offset of field: CREATE3res::CREATE3res_u"]
        [::std::mem::offset_of!(CREATE3res, CREATE3res_u) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct READ3args {
    pub file: nfs_fh3,
    pub offset: offset3,
    pub count: count3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of READ3args"][::std::mem::size_of::<READ3args>() - 32usize];
    ["Alignment of READ3args"][::std::mem::align_of::<READ3args>() - 8usize];
    ["Offset of field: READ3args::file"][::std::mem::offset_of!(READ3args, file) - 0usize];
    ["Offset of field: READ3args::offset"][::std::mem::offset_of!(READ3args, offset) - 16usize];
    ["Offset of field: READ3args::count"][::std::mem::offset_of!(READ3args, count) - 24usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct READ3resok {
    pub file_attributes: post_op_attr,
    pub count: count3,
    pub eof: u32,
    pub data: READ3resok__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct READ3resok__bindgen_ty_1 {
    pub data_len: u32,
    pub data_val: *mut ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of READ3resok__bindgen_ty_1"]
        [::std::mem::size_of::<READ3resok__bindgen_ty_1>() - 16usize];
    ["Alignment of READ3resok__bindgen_ty_1"]
        [::std::mem::align_of::<READ3resok__bindgen_ty_1>() - 8usize];
    ["Offset of field: READ3resok__bindgen_ty_1::data_len"]
        [::std::mem::offset_of!(READ3resok__bindgen_ty_1, data_len) - 0usize];
    ["Offset of field: READ3resok__bindgen_ty_1::data_val"]
        [::std::mem::offset_of!(READ3resok__bindgen_ty_1, data_val) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of READ3resok"][::std::mem::size_of::<READ3resok>() - 120usize];
    ["Alignment of READ3resok"][::std::mem::align_of::<READ3resok>() - 8usize];
    ["Offset of field: READ3resok::file_attributes"]
        [::std::mem::offset_of!(READ3resok, file_attributes) - 0usize];
    ["Offset of field: READ3resok::count"][::std::mem::offset_of!(READ3resok, count) - 96usize];
    ["Offset of field: READ3resok::eof"][::std::mem::offset_of!(READ3resok, eof) - 100usize];
    ["Offset of field: READ3resok::data"][::std::mem::offset_of!(READ3resok, data) - 104usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct READ3resfail {
    pub file_attributes: post_op_attr,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of READ3resfail"][::std::mem::size_of::<READ3resfail>() - 96usize];
    ["Alignment of READ3resfail"][::std::mem::align_of::<READ3resfail>() - 8usize];
    ["Offset of field: READ3resfail::file_attributes"]
        [::std::mem::offset_of!(READ3resfail, file_attributes) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct READ3res {
    pub status: nfsstat3,
    pub READ3res_u: READ3res__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union READ3res__bindgen_ty_1 {
    pub resok: READ3resok,
    pub resfail: READ3resfail,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of READ3res__bindgen_ty_1"][::std::mem::size_of::<READ3res__bindgen_ty_1>() - 120usize];
    ["Alignment of READ3res__bindgen_ty_1"]
        [::std::mem::align_of::<READ3res__bindgen_ty_1>() - 8usize];
    ["Offset of field: READ3res__bindgen_ty_1::resok"]
        [::std::mem::offset_of!(READ3res__bindgen_ty_1, resok) - 0usize];
    ["Offset of field: READ3res__bindgen_ty_1::resfail"]
        [::std::mem::offset_of!(READ3res__bindgen_ty_1, resfail) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of READ3res"][::std::mem::size_of::<READ3res>() - 128usize];
    ["Alignment of READ3res"][::std::mem::align_of::<READ3res>() - 8usize];
    ["Offset of field: READ3res::status"][::std::mem::offset_of!(READ3res, status) - 0usize];
    ["Offset of field: READ3res::READ3res_u"]
        [::std::mem::offset_of!(READ3res, READ3res_u) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct MKDIR3args {
    pub where_: diropargs3,
    pub attributes: sattr3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of MKDIR3args"][::std::mem::size_of::<MKDIR3args>() - 88usize];
    ["Alignment of MKDIR3args"][::std::mem::align_of::<MKDIR3args>() - 8usize];
    ["Offset of field: MKDIR3args::where_"][::std::mem::offset_of!(MKDIR3args, where_) - 0usize];
    ["Offset of field: MKDIR3args::attributes"]
        [::std::mem::offset_of!(MKDIR3args, attributes) - 24usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct MKDIR3resok {
    pub obj: post_op_fh3,
    pub obj_attributes: post_op_attr,
    pub dir_wcc: wcc_data,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of MKDIR3resok"][::std::mem::size_of::<MKDIR3resok>() - 248usize];
    ["Alignment of MKDIR3resok"][::std::mem::align_of::<MKDIR3resok>() - 8usize];
    ["Offset of field: MKDIR3resok::obj"][::std::mem::offset_of!(MKDIR3resok, obj) - 0usize];
    ["Offset of field: MKDIR3resok::obj_attributes"]
        [::std::mem::offset_of!(MKDIR3resok, obj_attributes) - 24usize];
    ["Offset of field: MKDIR3resok::dir_wcc"]
        [::std::mem::offset_of!(MKDIR3resok, dir_wcc) - 120usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct MKDIR3resfail {
    pub dir_wcc: wcc_data,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of MKDIR3resfail"][::std::mem::size_of::<MKDIR3resfail>() - 128usize];
    ["Alignment of MKDIR3resfail"][::std::mem::align_of::<MKDIR3resfail>() - 8usize];
    ["Offset of field: MKDIR3resfail::dir_wcc"]
        [::std::mem::offset_of!(MKDIR3resfail, dir_wcc) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct MKDIR3res {
    pub status: nfsstat3,
    pub MKDIR3res_u: MKDIR3res__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union MKDIR3res__bindgen_ty_1 {
    pub resok: MKDIR3resok,
    pub resfail: MKDIR3resfail,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of MKDIR3res__bindgen_ty_1"]
        [::std::mem::size_of::<MKDIR3res__bindgen_ty_1>() - 248usize];
    ["Alignment of MKDIR3res__bindgen_ty_1"]
        [::std::mem::align_of::<MKDIR3res__bindgen_ty_1>() - 8usize];
    ["Offset of field: MKDIR3res__bindgen_ty_1::resok"]
        [::std::mem::offset_of!(MKDIR3res__bindgen_ty_1, resok) - 0usize];
    ["Offset of field: MKDIR3res__bindgen_ty_1::resfail"]
        [::std::mem::offset_of!(MKDIR3res__bindgen_ty_1, resfail) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of MKDIR3res"][::std::mem::size_of::<MKDIR3res>() - 256usize];
    ["Alignment of MKDIR3res"][::std::mem::align_of::<MKDIR3res>() - 8usize];
    ["Offset of field: MKDIR3res::status"][::std::mem::offset_of!(MKDIR3res, status) - 0usize];
    ["Offset of field: MKDIR3res::MKDIR3res_u"]
        [::std::mem::offset_of!(MKDIR3res, MKDIR3res_u) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RENAME3args {
    pub from: diropargs3,
    pub to: diropargs3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RENAME3args"][::std::mem::size_of::<RENAME3args>() - 48usize];
    ["Alignment of RENAME3args"][::std::mem::align_of::<RENAME3args>() - 8usize];
    ["Offset of field: RENAME3args::from"][::std::mem::offset_of!(RENAME3args, from) - 0usize];
    ["Offset of field: RENAME3args::to"][::std::mem::offset_of!(RENAME3args, to) - 24usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct RENAME3resok {
    pub fromdir_wcc: wcc_data,
    pub todir_wcc: wcc_data,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RENAME3resok"][::std::mem::size_of::<RENAME3resok>() - 256usize];
    ["Alignment of RENAME3resok"][::std::mem::align_of::<RENAME3resok>() - 8usize];
    ["Offset of field: RENAME3resok::fromdir_wcc"]
        [::std::mem::offset_of!(RENAME3resok, fromdir_wcc) - 0usize];
    ["Offset of field: RENAME3resok::todir_wcc"]
        [::std::mem::offset_of!(RENAME3resok, todir_wcc) - 128usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct RENAME3resfail {
    pub fromdir_wcc: wcc_data,
    pub todir_wcc: wcc_data,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RENAME3resfail"][::std::mem::size_of::<RENAME3resfail>() - 256usize];
    ["Alignment of RENAME3resfail"][::std::mem::align_of::<RENAME3resfail>() - 8usize];
    ["Offset of field: RENAME3resfail::fromdir_wcc"]
        [::std::mem::offset_of!(RENAME3resfail, fromdir_wcc) - 0usize];
    ["Offset of field: RENAME3resfail::todir_wcc"]
        [::std::mem::offset_of!(RENAME3resfail, todir_wcc) - 128usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct RENAME3res {
    pub status: nfsstat3,
    pub RENAME3res_u: RENAME3res__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union RENAME3res__bindgen_ty_1 {
    pub resok: RENAME3resok,
    pub resfail: RENAME3resfail,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RENAME3res__bindgen_ty_1"]
        [::std::mem::size_of::<RENAME3res__bindgen_ty_1>() - 256usize];
    ["Alignment of RENAME3res__bindgen_ty_1"]
        [::std::mem::align_of::<RENAME3res__bindgen_ty_1>() - 8usize];
    ["Offset of field: RENAME3res__bindgen_ty_1::resok"]
        [::std::mem::offset_of!(RENAME3res__bindgen_ty_1, resok) - 0usize];
    ["Offset of field: RENAME3res__bindgen_ty_1::resfail"]
        [::std::mem::offset_of!(RENAME3res__bindgen_ty_1, resfail) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RENAME3res"][::std::mem::size_of::<RENAME3res>() - 264usize];
    ["Alignment of RENAME3res"][::std::mem::align_of::<RENAME3res>() - 8usize];
    ["Offset of field: RENAME3res::status"][::std::mem::offset_of!(RENAME3res, status) - 0usize];
    ["Offset of field: RENAME3res::RENAME3res_u"]
        [::std::mem::offset_of!(RENAME3res, RENAME3res_u) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct READDIRPLUS3args {
    pub dir: nfs_fh3,
    pub cookie: cookie3,
    pub cookieverf: cookieverf3,
    pub dircount: count3,
    pub maxcount: count3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of READDIRPLUS3args"][::std::mem::size_of::<READDIRPLUS3args>() - 40usize];
    ["Alignment of READDIRPLUS3args"][::std::mem::align_of::<READDIRPLUS3args>() - 8usize];
    ["Offset of field: READDIRPLUS3args::dir"]
        [::std::mem::offset_of!(READDIRPLUS3args, dir) - 0usize];
    ["Offset of field: READDIRPLUS3args::cookie"]
        [::std::mem::offset_of!(READDIRPLUS3args, cookie) - 16usize];
    ["Offset of field: READDIRPLUS3args::cookieverf"]
        [::std::mem::offset_of!(READDIRPLUS3args, cookieverf) - 24usize];
    ["Offset of field: READDIRPLUS3args::dircount"]
        [::std::mem::offset_of!(READDIRPLUS3args, dircount) - 32usize];
    ["Offset of field: READDIRPLUS3args::maxcount"]
        [::std::mem::offset_of!(READDIRPLUS3args, maxcount) - 36usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct entryplus3 {
    pub fileid: fileid3,
    pub name: filename3,
    pub cookie: cookie3,
    pub name_attributes: post_op_attr,
    pub name_handle: post_op_fh3,
    pub nextentry: *mut entryplus3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of entryplus3"][::std::mem::size_of::<entryplus3>() - 152usize];
    ["Alignment of entryplus3"][::std::mem::align_of::<entryplus3>() - 8usize];
    ["Offset of field: entryplus3::fileid"][::std::mem::offset_of!(entryplus3, fileid) - 0usize];
    ["Offset of field: entryplus3::name"][::std::mem::offset_of!(entryplus3, name) - 8usize];
    ["Offset of field: entryplus3::cookie"][::std::mem::offset_of!(entryplus3, cookie) - 16usize];
    ["Offset of field: entryplus3::name_attributes"]
        [::std::mem::offset_of!(entryplus3, name_attributes) - 24usize];
    ["Offset of field: entryplus3::name_handle"]
        [::std::mem::offset_of!(entryplus3, name_handle) - 120usize];
    ["Offset of field: entryplus3::nextentry"]
        [::std::mem::offset_of!(entryplus3, nextentry) - 144usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dirlistplus3 {
    pub entries: *mut entryplus3,
    pub eof: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dirlistplus3"][::std::mem::size_of::<dirlistplus3>() - 16usize];
    ["Alignment of dirlistplus3"][::std::mem::align_of::<dirlistplus3>() - 8usize];
    ["Offset of field: dirlistplus3::entries"]
        [::std::mem::offset_of!(dirlistplus3, entries) - 0usize];
    ["Offset of field: dirlistplus3::eof"][::std::mem::offset_of!(dirlistplus3, eof) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct READDIRPLUS3resok {
    pub dir_attributes: post_op_attr,
    pub cookieverf: cookieverf3,
    pub reply: dirlistplus3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of READDIRPLUS3resok"][::std::mem::size_of::<READDIRPLUS3resok>() - 120usize];
    ["Alignment of READDIRPLUS3resok"][::std::mem::align_of::<READDIRPLUS3resok>() - 8usize];
    ["Offset of field: READDIRPLUS3resok::dir_attributes"]
        [::std::mem::offset_of!(READDIRPLUS3resok, dir_attributes) - 0usize];
    ["Offset of field: READDIRPLUS3resok::cookieverf"]
        [::std::mem::offset_of!(READDIRPLUS3resok, cookieverf) - 96usize];
    ["Offset of field: READDIRPLUS3resok::reply"]
        [::std::mem::offset_of!(READDIRPLUS3resok, reply) - 104usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct READDIRPLUS3resfail {
    pub dir_attributes: post_op_attr,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of READDIRPLUS3resfail"][::std::mem::size_of::<READDIRPLUS3resfail>() - 96usize];
    ["Alignment of READDIRPLUS3resfail"][::std::mem::align_of::<READDIRPLUS3resfail>() - 8usize];
    ["Offset of field: READDIRPLUS3resfail::dir_attributes"]
        [::std::mem::offset_of!(READDIRPLUS3resfail, dir_attributes) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct READDIRPLUS3res {
    pub status: nfsstat3,
    pub READDIRPLUS3res_u: READDIRPLUS3res__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union READDIRPLUS3res__bindgen_ty_1 {
    pub resok: READDIRPLUS3resok,
    pub resfail: READDIRPLUS3resfail,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of READDIRPLUS3res__bindgen_ty_1"]
        [::std::mem::size_of::<READDIRPLUS3res__bindgen_ty_1>() - 120usize];
    ["Alignment of READDIRPLUS3res__bindgen_ty_1"]
        [::std::mem::align_of::<READDIRPLUS3res__bindgen_ty_1>() - 8usize];
    ["Offset of field: READDIRPLUS3res__bindgen_ty_1::resok"]
        [::std::mem::offset_of!(READDIRPLUS3res__bindgen_ty_1, resok) - 0usize];
    ["Offset of field: READDIRPLUS3res__bindgen_ty_1::resfail"]
        [::std::mem::offset_of!(READDIRPLUS3res__bindgen_ty_1, resfail) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of READDIRPLUS3res"][::std::mem::size_of::<READDIRPLUS3res>() - 128usize];
    ["Alignment of READDIRPLUS3res"][::std::mem::align_of::<READDIRPLUS3res>() - 8usize];
    ["Offset of field: READDIRPLUS3res::status"]
        [::std::mem::offset_of!(READDIRPLUS3res, status) - 0usize];
    ["Offset of field: READDIRPLUS3res::READDIRPLUS3res_u"]
        [::std::mem::offset_of!(READDIRPLUS3res, READDIRPLUS3res_u) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct sattrguard3 {
    pub check: u32,
    pub sattrguard3_u: sattrguard3__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union sattrguard3__bindgen_ty_1 {
    pub obj_ctime: nfstime3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sattrguard3__bindgen_ty_1"]
        [::std::mem::size_of::<sattrguard3__bindgen_ty_1>() - 8usize];
    ["Alignment of sattrguard3__bindgen_ty_1"]
        [::std::mem::align_of::<sattrguard3__bindgen_ty_1>() - 4usize];
    ["Offset of field: sattrguard3__bindgen_ty_1::obj_ctime"]
        [::std::mem::offset_of!(sattrguard3__bindgen_ty_1, obj_ctime) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sattrguard3"][::std::mem::size_of::<sattrguard3>() - 12usize];
    ["Alignment of sattrguard3"][::std::mem::align_of::<sattrguard3>() - 4usize];
    ["Offset of field: sattrguard3::check"][::std::mem::offset_of!(sattrguard3, check) - 0usize];
    ["Offset of field: sattrguard3::sattrguard3_u"]
        [::std::mem::offset_of!(sattrguard3, sattrguard3_u) - 4usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct SETATTR3args {
    pub object: nfs_fh3,
    pub new_attributes: sattr3,
    pub guard: sattrguard3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SETATTR3args"][::std::mem::size_of::<SETATTR3args>() - 96usize];
    ["Alignment of SETATTR3args"][::std::mem::align_of::<SETATTR3args>() - 8usize];
    ["Offset of field: SETATTR3args::object"]
        [::std::mem::offset_of!(SETATTR3args, object) - 0usize];
    ["Offset of field: SETATTR3args::new_attributes"]
        [::std::mem::offset_of!(SETATTR3args, new_attributes) - 16usize];
    ["Offset of field: SETATTR3args::guard"][::std::mem::offset_of!(SETATTR3args, guard) - 80usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct SETATTR3resok {
    pub obj_wcc: wcc_data,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SETATTR3resok"][::std::mem::size_of::<SETATTR3resok>() - 128usize];
    ["Alignment of SETATTR3resok"][::std::mem::align_of::<SETATTR3resok>() - 8usize];
    ["Offset of field: SETATTR3resok::obj_wcc"]
        [::std::mem::offset_of!(SETATTR3resok, obj_wcc) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct SETATTR3resfail {
    pub obj_wcc: wcc_data,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SETATTR3resfail"][::std::mem::size_of::<SETATTR3resfail>() - 128usize];
    ["Alignment of SETATTR3resfail"][::std::mem::align_of::<SETATTR3resfail>() - 8usize];
    ["Offset of field: SETATTR3resfail::obj_wcc"]
        [::std::mem::offset_of!(SETATTR3resfail, obj_wcc) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct SETATTR3res {
    pub status: nfsstat3,
    pub SETATTR3res_u: SETATTR3res__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union SETATTR3res__bindgen_ty_1 {
    pub resok: SETATTR3resok,
    pub resfail: SETATTR3resfail,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SETATTR3res__bindgen_ty_1"]
        [::std::mem::size_of::<SETATTR3res__bindgen_ty_1>() - 128usize];
    ["Alignment of SETATTR3res__bindgen_ty_1"]
        [::std::mem::align_of::<SETATTR3res__bindgen_ty_1>() - 8usize];
    ["Offset of field: SETATTR3res__bindgen_ty_1::resok"]
        [::std::mem::offset_of!(SETATTR3res__bindgen_ty_1, resok) - 0usize];
    ["Offset of field: SETATTR3res__bindgen_ty_1::resfail"]
        [::std::mem::offset_of!(SETATTR3res__bindgen_ty_1, resfail) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SETATTR3res"][::std::mem::size_of::<SETATTR3res>() - 136usize];
    ["Alignment of SETATTR3res"][::std::mem::align_of::<SETATTR3res>() - 8usize];
    ["Offset of field: SETATTR3res::status"][::std::mem::offset_of!(SETATTR3res, status) - 0usize];
    ["Offset of field: SETATTR3res::SETATTR3res_u"]
        [::std::mem::offset_of!(SETATTR3res, SETATTR3res_u) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nfs_fh {
    pub len: ::std::os::raw::c_int,
    pub val: *mut ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nfs_fh"][::std::mem::size_of::<nfs_fh>() - 16usize];
    ["Alignment of nfs_fh"][::std::mem::align_of::<nfs_fh>() - 8usize];
    ["Offset of field: nfs_fh::len"][::std::mem::offset_of!(nfs_fh, len) - 0usize];
    ["Offset of field: nfs_fh::val"][::std::mem::offset_of!(nfs_fh, val) - 8usize];
};
unsafe extern "C" {
    pub fn nfs_get_rootfh(nfs: *mut nfs_context) -> *const nfs_fh;
}
